### PR TITLE
Ignore log directory

### PR DESCRIPTION
**Pull request by fredlawl**
Adding a blank .gitignore does not fully ignore all files in the directory. Fix this by adding these rules.

### CODE REVIEW

**Comment by grantholle** [comment]
Fred! I ignore log files in my root `.ignore` 😛

**Comment by fredlawl** [comment]
Yes, but they're just .log files. Not the directory itself.

**Comment by grantholle** [comment]
I _want_ the log directory included because that's where I keep my logs... I didn't want to create it manually when start the logger because I'm lazy. I put the .gitignore there because I wanted it in source control...

**Comment by fredlawl** [comment]
> I want the log directory included because that's where I keep my logs... I didn't want to create it manually when start the logger because I'm lazy. I put the .gitignore there because I wanted it in source control...

I get that, but my pull request makes it so that the directory is still in source control, and no other files can be added to it and accidentally committed :)

**Pull request merged**
